const keywords = [
  // Brand and General E-commerce
  "Ita Luxury",
  "Tunisie e-commerce",
  "boutique en ligne haut de gamme",
  "achat en ligne Tunisie",
  "shopping luxe Tunisie",
  "plateforme e-commerce premium",
  "Ita Luxury online store",
  "premium online shopping Tunisia",
  "high-end online boutique",
  "luxury shopping in Tunisia",
  "موقع ايطا للرفاهية",
  "تجارة الكترونية تونس",
  "متجر فاخر على الإنترنت",
  "فخامة تسوق إيطة",

  // Home Essentials
  "essentiels pour la maison",
  "décoration intérieure luxe",
  "ameublement haut de gamme",
  "accessoires maison designer",
  "articles ménagers de qualité",
  "literie de luxe",
  "arts de la table raffinés",
  "luminaires design",
  "textiles maison premium",
  "home essentials",
  "luxury home decor",
  "high-end furniture",
  "designer home accessories",
  "الضروريات المنزلية",
  "ديكور منزلي فاخر",
  "أثاث عالي الجودة",
  "خدمات التنظيف الفاخر",
  "مستلزمات المنزل الفاخرة",

  // Luxury Items
  "produits de luxe Tunisie",
  "marques de prestige",
  "accessoires de luxe",
  "montres de luxe",
  "bijoux haut de gamme",
  "maroquinerie de luxe",
  "parfums et cosmétiques de marque",
  "mode designer",
  "chaussures de créateur",
  "luxury products Tunisia",
  "prestigious brands",
  "luxury watches",
  "high-end jewelry",
  "luxury leather goods",
  "مجوهرات فاخرة",
  "أحذية مصممة",
  "عطور فاخرة",
  "منتجات عالمية فاخرة",

  // Shopping Experience
  "expérience shopping premium",
  "service clientèle personnalisé",
  "emballage cadeau luxe",
  "livraison express",
  "garantie authenticité",
  "retours faciles",
  "paiement sécurisé",
  "premium shopping experience",
  "personalized customer service",
  "luxury gift wrapping",
  "express delivery",
  "easy returns",
  "secure payment",
  "تجربة تسوق فاخرة",
  "خدمة العملاء المخصصة",
  "تسليم سريع",
  "ضمان الجودة",

  // Product Categories
  "électroménager haut de gamme",
  "technologie dernier cri",
  "mobilier contemporain",
  "art et objets de collection",
  "vins et spiritueux fins",
  "articles de cuisine professionnels",
  "high-end appliances",
  "cutting-edge technology",
  "contemporary furniture",
  "art and collectibles",
  "fine wines and spirits",
  "professional kitchen items",
  "الأجهزة المنزلية الفاخرة",
  "تكنولوجيا حديثة",
  "أثاث عصري",
  "تكنولوجيا منزلية ذكية",
  "منتجات كهربائية فاخرة",

  // Special Offers
  "offres exclusives",
  "ventes privées",
  "collections limitées",
  "nouveautés luxe",
  "promotions articles premium",
  "exclusive offers",
  "private sales",
  "limited collections",
  "luxury new arrivals",
  "premium product promotions",
  "عروض حصرية",
  "تخفيضات خاصة",
  "مجموعات محدودة",
  "تخفيضات موسمية",
  "عروض نهاية السنة",

  // Customer Engagement
  "programme de fidélité VIP",
  "conseils déco personnalisés",
  "guide des tendances luxe",
  "blog lifestyle haut de gamme",
  "VIP loyalty program",
  "personalized decor advice",
  "luxury trends guide",
  "high-end lifestyle blog",
  "برنامج ولاء عملاء VIP",
  "نصائح ديكور مخصصة",
  "دليل اتجاهات الرفاهية",
  "محتوى تفاعلي",
  "مجتمع عملاء الفخامة",

  // SEO Optimization
  "meilleur site e-commerce Tunisie",
  "acheter produits luxe en ligne",
  "livraison internationale luxe",
  "cadeaux haut de gamme",
  "shopping en ligne sécurisé",
  "best e-commerce site Tunisia",
  "buy luxury products online",
  "international luxury delivery",
  "high-end gifts",
  "secure online shopping",
  "أفضل موقع تجارة إلكترونية في تونس",
  "شراء المنتجات الفاخرة عبر الإنترنت",
  "توصيل دولي فخم",
  "تجارة إلكترونية آمنة",

  // Seasonal and Occasional
  "idées cadeaux luxe",
  "décorations festives haut de gamme",
  "collection été luxe",
  "essentiels hiver premium",
  "luxury gift ideas",
  "high-end festive decorations",
  "luxury summer collection",
  "premium winter essentials",
  "أفكار هدايا فاخرة",
  "زينة احتفالية عالية الجودة",
  "مجموعة صيفية فاخرة",
  "أفكار هدايا لعيد الميلاد",
  "احتفالات مميزة",

  // Trust and Quality
  "produits authentiques garantis",
  "sélection rigoureuse",
  "excellence du service",
  "satisfaction client prioritaire",
  "guaranteed authentic products",
  "stringent selection",
  "service excellence",
  "customer satisfaction priority",
  "منتجات أصلية مضمونة",
  "اختيار صارم",
  "تميز الخدمة",
  "شهادات موثوقة",
  "تقييمات عملاء ممتازة",

  // Checkout Process
  "processus d'achat simplifié",
  "paiement en ligne sécurisé Tunisie",
  "options de livraison flexibles",
  "suivi de commande en temps réel",
  "simplified checkout process",
  "secure online payment Tunisia",
  "flexible delivery options",
  "real-time order tracking",
  "عملية شراء مبسطة",
  "دفع آمن عبر الإنترنت في تونس",
  "خيارات توصيل مرنة",
  "إجراءات سريعة للدفع",
  "تجربة تسوق سلسة",

  // Mobile and Tech
  "application mobile shopping luxe",
  "expérience d'achat omnicanal",
  "réalité augmentée essayage virtuel",
  "luxury shopping mobile app",
  "omnichannel shopping experience",
  "augmented reality virtual fitting",
  "تطبيق تسوق فاخر",
  "تجربة تسوق متعددة القنوات",
  "تقنية الواقع المعزز لتجربة افتراضية",
  "تطبيقات تسوق مريحة",
  "تجارب تسوق مبتكرة",

  // Sustainability
  "produits luxe durables",
  "emballages éco-responsables",
  "marques éthiques premium",
  "sustainable luxury products",
  "eco-friendly packaging",
  "premium ethical brands",
  "المنتجات الفاخرة المستدامة",
  "تغليف صديق للبيئة",
  "علامات تجارية أخلاقية عالية الجودة",
  "التسوق المستدام",
  "ممارسات تجارية مسؤولة",
];

export default keywords;
