
const keywords = [
    "vente en ligne",
    "Tunisie",
    "offres exclusives",
    "promotions",
    "achat en ligne",
    "produits Tunisie",
    "Maison Ng",
    "nouveaux produits",
    "produits en promotion",
    "achat sécurisé",
    "livraison rapide",
    "meilleures offres",
    "produits électroniques",
    "mode et accessoires",
    "équipements maison",
    "meilleures marques",
    "produits de qualité",
    "shopping en ligne",
    "e-commerce Tunisie",
    "boutique en ligne",
    "cadeaux",
    "vente flash",
    "meilleur prix",
    "offre spéciale",
    "dernière chance",
    "satisfaction garantie",
    "service clientèle",
    "commande facile",
    "paiement sécurisé",
    "articles populaires",
    "beauté et bien-être",
    "jouets pour enfants",
    "décoration intérieure",
    "accessoires informatiques",
    "produits de jardinage",
    "vêtements pour hommes",
    "vêtements pour femmes",
    "chaussures de qualité",
    "accessoires de mode",
    "idées de cadeaux",
    "articles de cuisine",
    "outils de bricolage",
    "meubles modernes",
    "produits de santé",
    "accessoires pour animaux",
    "montres de luxe",
    "bijoux élégants",
    "sacs à main tendance",
  ];
  
  export default keywords;
  